 
version: '2'
services:
  
  api:
    build: .
    # Auto restart server after change code           : nodemon
    command: nodemon app.js
    working_dir: /usr/app/
    volumes:
      - ./:/usr/app/
    ports:
      - "3232:3232"
      #- "8701:8701"  
    environment:
      # development or production
      NODE_ENV: development
      NODE_PORT: 3232

      FEDEX_KEY: jfjwKS65xft8r8mh
      FEDEX_PASSWORD: QYrbniTyMafyj4LXm4tV7nsq5
      FEDEX_ACCOUNT: 802388543
      FEDEX_METER: 119147906
      FEDEX_DEMO: true

      DB_HOST: host
      DB_PORT: 5432
      DB_NAME: dbname
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      DB_MAX: 100
      DB_IDLE_TIMEOUT: 7000
      DB_CONNECTION_TIMEOUT: 7000

  #postgres:
    #image: postgres:9.6.2-alpine
    #environment:
     # POSTGRES_USER: postgres
     # POSTGRES_PASSWORD: postgres
     # POSTGRES_DB: dbname
    #ports:
     # - "5433:5432" 
    #volumes:
      #- ./:/var/lib/postgresql
